### ISSUE TITLE
Bump faraday version upto 2

### ISSUE THREAD

**Issue by HudsonAfonso** [mikamai/onesignal-ruby#38]
Bump faraday version upto 2

**Comment by ghost** [comment]
@bernardini687, I have created PR[#41](https://github.com/mikamai/onesignal-ruby/pull/41). Why don't you want to merge it? Thank you

**Comment by MatteoJoliveau** [comment]
Sorry, @yuri-zubov-fortune. This package has seen very low usage on our (@mikamai) part, so we're not very active with its maintenance due to a lack of bandwidth. 

I will evaluate internally if it may be feasible to add external maintainers if anyone is willing to step up, or if a copyright and ownership transfer can be done if anyone wants to adopt it. Otherwise, I'm afraid our best shot is to abandon this package as we are unable to continue its maintenance at the moment, and development can continue on forks.
