### ISSUE TITLE
How to send push including android_channel_id 

### ISSUE THREAD

**Issue by bismark64** [mikamai/onesignal-ruby#4]
Looking at the docs, it's not clear how to include parameters listed in: 

https://documentation.onesignal.com/reference#section-appearance

Thanks!

**Comment by MatteoJoliveau** [comment]
Not all of the parameters are supported. Since there are so many we are basically adding them on-demand whenever a use case shows up. 
If you need to customize the Android channel you can either submit a PR (which are always very welcome!) or wait until we add it ourselves, but it may take a while depending on our spare time availability.

**Comment by rafayet-monon** [comment]
@bismark64 I have added some additional parameters, though I forked it from this repo and edited some code. If you want you can check [This Repo](https://github.com/rafayet-monon/onesignal).

**Comment by MatteoJoliveau** [comment]
We're doing a bit of cleanup, if you need some specific fields to be added feel free to reopen this issue or submit a PR to add them! 👍🏻
