### ISSUE TITLE
Can't install the gem using Rails 6

### ISSUE THREAD

**Issue by LuisDeHaro** [mikamai/onesignal-ruby#9]
Hi, I'm trying to install the gem in my Rails 6.0.0 project and I'm getting the following error:

~$ bundle
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "activesupport":
  In snapshot (Gemfile.lock):
    activesupport (= 6.0.0)

  In Gemfile:
    onesignal-ruby (~> 0.3.0) was resolved to 0.3.0, which depends on
      activesupport (>= 5.0.0, ~> 5.0)

    rails (~> 6.0.0) was resolved to 6.0.0, which depends on
      activesupport (= 6.0.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

I just found this gem and it looks promising! thanks in advance.

**Comment by MatteoJoliveau** [comment]
Hi @LuisDeHaro, thank you for bringing this up!

I think we can definitely drop ActiveSupport as a dependency, it's basically just there for a couple of utility functions that we can implement ourselves.

This would resolve any incompatibility with Rails 6.

I'll try to scrape some time off to do this (or I'll find a colleague that is available to do it), I'll let you know asap.

Otherwise, if anyone is willing to tackle this, we'll gladly accept a PR!

**Comment by christophemaximin** [comment]
@MatteoJoliveau  [Activesupport is a dependency of factory_bot](https://github.com/thoughtbot/factory_bot/blob/6ccbb8735bb8027adb11694ca1020d2c8ae0469d/factory_bot.gemspec#L25), used in this gem, so I don't believe there's a real way of running the tests without activesupport present.

So I think we're presented with two choices:
- Keep activesupport as a dependency, but set its required version the same as factory_bot (>=3.0.0) (quick and easy)
- Remove factory_bot entirely and rewrite the corresponding code manually.

Any preference?

**Comment by bernardini687** [comment]
Hi @christophemaximin, thanks for your comment!

I wouldn't worry about about **factory_bot** now, since that is purely a development concern.
The current issue is to get the gem up and running in a Rails 6 project.
What I'm going to try is to loosen up the requirements for **activesupport** as a runtime dependency, so that it accepts versions `>= 5.0.0` and `< 7.0` 👍

**Comment by christophemaximin** [comment]
> I wouldn't worry about about factory_bot now, since that is purely a development concern.
> The current issue is to get the gem up and running in a Rails 6 project.

I do understand that, but the previous comment mentionned "I think we can definitely drop ActiveSupport as a dependency", which we can do as a runtime dependency, but because it's a development dependency, you wouldn't be able to run the tests without activesupport :)
For example you can remove the activesupport from the gemspec line, which will obviously make the gem fail to work, but the tests will still (incorrectly) pass because it's a dependency of factorybot.

If loosening the version requirements for AS is enough rather than removing it, that's simpler and good too!

**Comment by LuisDeHaro** [comment]
Hi @MatteoJoliveau & @christophemaximin,

I see that you guys have worked on the issue, thank you guys!

In order to use this gem with Rails 6, what should I do? 

I see this gem in rubygems:

https://rubygems.org/gems/onesignal-ruby-rails6

Is that the one that I need to add in my Gemfile?

Thanks!

**Comment by MatteoJoliveau** [comment]
Hi @LuisDeHaro, we are adding this feature to version 0.4.0, which will be released soon-ish (I would like to merge [this PR]( #7 ) before releasing it). In the meantime, you could point Bundle to the `develop` branch with this:
`gem 'onesignal-ruby', github: 'mikamai/onesignal-ruby', branch: 'develop'`

And then migrate to the stable version once it's live on RubyGems
